name: On-demand self publishing

permissions:
  contents: read
  pull-requests: write
  issues: write
  checks: read

on:
  issue_comment:
    types: [created]

jobs:

  config:
    if: github.repository_owner == 'MicrosoftDocs' && contains(github.event.repository.topics, 'build')
    runs-on: ubuntu-latest
    outputs:
      EnableAfterHoursPublish: ${{ steps.read.outputs.EnableAfterHoursPublish }}
      EnableServicingPublish: ${{ steps.read.outputs.EnableServicingPublish }}
      AfterHoursAuthorizedTeam: ${{ steps.read.outputs.AfterHoursAuthorizedTeam }}
      ServicingAuthorizedTeam: ${{ steps.read.outputs.ServicingAuthorizedTeam }}
      ServicingAuthorizedApps: ${{ steps.read.outputs.ServicingAuthorizedApps }}
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: .github/workflow-config.json
          sparse-checkout-cone-mode: false
      - id: read
        shell: pwsh
        run: |
          $Config = (Get-Content '.github/workflow-config.json' | ConvertFrom-Json).OnDemandPublish
          "EnableAfterHoursPublish=$("$($Config.EnableAfterHoursPublish)".ToLower())" >> $Env:GITHUB_OUTPUT
          "EnableServicingPublish=$("$($Config.EnableServicingPublish)".ToLower())" >> $Env:GITHUB_OUTPUT
          "AfterHoursAuthorizedTeam=$($Config.AfterHoursAuthorizedTeam)" >> $Env:GITHUB_OUTPUT
          "ServicingAuthorizedTeam=$($Config.ServicingAuthorizedTeam)" >> $Env:GITHUB_OUTPUT
          "ServicingAuthorizedApps=$(($Config.ServicingAuthorizedApps -join ','))" >> $Env:GITHUB_OUTPUT

  on-demand-publish:
    if: github.repository_owner == 'MicrosoftDocs' && contains(github.event.repository.topics, 'build')
    needs: config
    uses: MicrosoftDocs/tcp-workflows/.github/workflows/Shared-OnDemandPublish.yml@main
    with:
        PayloadJson: ${{ toJSON(github) }}
        EnableAfterHoursPublish: ${{ fromJSON(needs.config.outputs.EnableAfterHoursPublish) }}
        EnableServicingPublish: ${{ fromJSON(needs.config.outputs.EnableServicingPublish) }}
        AfterHoursAuthorizedTeam: ${{ needs.config.outputs.AfterHoursAuthorizedTeam }}
        ServicingAuthorizedTeam: ${{ needs.config.outputs.ServicingAuthorizedTeam }}
        ServicingAuthorizedApps: ${{ needs.config.outputs.ServicingAuthorizedApps }}
    secrets:
        AccessToken: ${{ secrets.GITHUB_TOKEN }}
        PrivateKey: ${{ secrets.M365_APP_PRIVATE_KEY }}
        ClientId: ${{ secrets.M365_APP_CLIENT_ID }}
 